function Af = A_matrix(in1,in2)
%A_matrix
%    Af = A_matrix(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    26-Apr-2023 18:53:08

q3 = in1(3,:);
q4 = in1(4,:);
t2 = cos(q4);
t3 = sin(q4);
Af = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t2,t3,-1.0,0.0,0.0,-q3.*t3,q3.*t2,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0],[5,5]);
end
