function Bf = B_matrix
%B_matrix
%    Bf = B_matrix

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    27-Apr-2023 11:33:57

Bf = reshape([0.0,0.0,2.0,0.0,-5.0./2.0,0.0,0.0,2.0,0.0,5.0./2.0],[5,2]);
end
