function Bf = B_matrix(in1,in2)
%B_matrix
%    Bf = B_matrix(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    26-Apr-2023 18:53:08

Bf = reshape([0.0,0.0,2.0,0.0,-5.0./2.0,0.0,0.0,2.0,0.0,5.0./2.0],[5,2]);
end
