function b = bfunc(T,Tmax)
%BFUNC
%    B = BFUNC(T,Tmax)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    26-Apr-2023 18:42:47

b = [Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax];
end
