function b = bfunc(T,Tmax)
%BFUNC
%    B = BFUNC(T,Tmax)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    27-Apr-2023 11:34:09

b = [Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax;Tmax];
end
