function q_dot = odefun_torque(in1,in2,L,M,d,J,R,b)
%ODEFUN_TORQUE
%    Q_DOT = ODEFUN_TORQUE(IN1,IN2,L,M,D,J,R,B)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    16-Mar-2023 17:09:12

% qdot = odefun_torque(q, u, ...)

q3 = in1(3,:);
q4 = in1(4,:);
q5 = in1(5,:);
u1 = in2(1,:);
u2 = in2(2,:);
t2 = d.^2;
t3 = 1.0./R;
t4 = M.*t2;
t5 = J+t4;
t6 = 1.0./t5;
%q_dot = [q3.*cos(q4);q3.*sin(q4);-b.*q3+d.*q5.^2+(t3.*(u1+u2))./M;q5;-L.*t3.*t6.*(u1-u2)-M.*d.*q3.*q5.*t6];
q_dot = [q3.*cos(q4);q3.*sin(q4);+d.*q5.^2+(t3.*(u1+u2))./M;q5;-L.*t3.*t6.*(u1-u2)-M.*d.*q3.*q5.*t6];